---
title: Classification of Quadratic Forms over $\mathbb Q$
author: "Shubin Xue"
institute: Beijing Institute of Technology
date: "2025/09/11"
bibliography: index.bib
lang: en

abstract: "A reading guidance of the first part of J. P. Serre's *A Course in Arithmetic*"

slide-level: 3

format:
  html: default
  beamer:
    toc: true
    custom-color:
        remark: "green!32!black"

---

### Notations

- $K$: an arbitrary field and $\operatorname{char}K \neq 2$. 

- $X$, $Y$, $Z$: variables.

- $\mathbb{P}$: the set of prime numbers.
    - $p\in\mathbb{P}$.
    - $\mathbb Q_p$: the completion of $\mathbb Q$ at $p$.

- $\mathbb{V}$=$\mathbb{P}\cup\{\infty\}$.
    - $v\in\mathbb{V}$.
    - $\mathbb Q_\infty=\mathbb{R}$

- Denote by the same letter an element and its class modulo. 

# Background and Approaches

## Classification and Representation

### Quadratic Froms

- $f(\vec{X})=\sum_{i,j=1}^n a_{ij} X_i X_j$ is a quadratic form
    - $\vec{X}=(X_1,\cdots,X_n)\in K^n$ and $a_{ij}=a_{ji}\in K$.

\vspace{0.5cm}

- The matrix $A_f=(a_{ij})$ associated with $f$ is Symmetric. 
    - $f(\vec{X})=\vec{X}^TA_f\vec{X}$.

\vspace{0.5cm}

- The pair $(K^n, f)$ is a quadratic space.
    - $f \sim g$: $\exists P\in GL(n,K)$ s.t. $A_f=P^TA_gP$.

\vspace{0.5cm}

- $f(X_1,\cdots,X_n)$ and $g(X_1,\cdots,X_m)$
$$
f\oplus g=f(X_1,\cdots,X_n)+g(X_{n+1},\cdots,X_{n+m})
$$

### Background(17-18th century)
<!-- 
As early as the early development of number theory, mathematicians began to pay attention to the representation problem of quadratic forms.

In the 19th century, mathematicians gradually discovered subtle connections between these problems.
-->
:::{#thm-fermat}
## Fermat's Two-Square Theorem
An odd prime $p$ can be represented as the sum of two squares if and only if $p\equiv1\pmod{4}$.
:::

\vspace{0.7cm}

:::{#thm-gauss}
## Gauss's Three-Square Theorem 
All positive integers except those of the form $4^a(8m-1)$ can be represented as the sum of three squares.
:::

### Background(19-20th century)
<!--
With the development of algebraic number theory, mathematicians extended Gauss's ideas to the field of rational numbers. By utilizing the properties of "local fields" (the real numbers and $p$-adic fields), they further strengthened the logical connection between classification and representation of numbers.
-->

:::{#thm-gauss-classification}
## Gauss's Classification of Quadratic Forms
Quadratic forms in the same equivalence class represent exactly the same set of numbers.
:::

\vspace{0.7cm}

:::{#thm-hasse-minkowski}
## Hasse-Minkowski
$f$ represents $0$ over $\mathbb Q$ iff it represents $0$ over all $\mathbb Q_v$.
:::

### Representing Numbers

- $f$ represents $a \in K$: $\exists 0\neq x \in K^n$ s.t. $f(x) = a$.

:::{#prp-represent}
Let $a \in K^\times$. TFAE:

- $f$ represents $a$
- $f \sim f_1 \oplus aZ^2$ where $f_1$ is of rank $\operatorname{rank} f - 1$.
- $f_a=f \oplus -aZ^2$ represents $0$.
:::

:::{#cor-hasse-minkowski}
## Hasse-Minkowski Theorem
$f$ represents $a\in\mathbb Q^\times$ over $\mathbb Q$ iff it represents $a$ over all $\mathbb Q_v$.
:::

- Apply Hasse-Minkowski Theorem to $f_a=f \oplus -aZ^2$.

<!--

- To check if $a$ can be represented by $f$, it suffices to examine when a quadratic form represents $0$.

- Suppose $f_1$ and $f_2$ can both represent some $a\in K^\times$, then we hope to reduce their rank and use induction in subsequent proofs. 

-->

## Local-to-Global Principle

### Decomposing quadratic spaces {.fragile}

<!--
If a quadratic space $(V, Q)$ has two isometric subspaces $U$ and $W$, then by Witt's theorem, the isometry can be extended to an automorphism of $V$. By restricting this automorphism to $U^\perp$, we see that $U^\perp$ and $W^\perp$ are also isometric.
-->

:::{#thm-witt-cancel}

## Witt's cancellation 

$f_1 \oplus g_1 \sim f_2 \oplus g_2$ and  $g_1 \sim g_2$ implies $f_1 \sim f_2$.
:::

- $(V, Q)$: A quadratic space.
- $(U, Q)$ and $(W, Q)$: Isomorphic subspaces.


:::{#fig-tikzcd-quiver}

```{tikz}
\begin{tikzcd}
	V & V && V & V \\
	U & W && {U^\perp} & {W^\perp}
	\arrow["\cong", dashed, no head, from=1-1, to=1-2]
	\arrow[no head, from=1-2, to=2-2]
	\arrow["\cong", from=1-4, to=1-5]
	\arrow["{\text{Restrict}}"', dashed, no head, from=1-4, to=2-4]
	\arrow[dashed, no head, from=1-5, to=2-5]
	\arrow["{\text{Lift}}", no head, from=2-1, to=1-1]
	\arrow["\cong", from=2-1, to=2-2]
	\arrow["\cong", from=2-4, to=2-5]
\end{tikzcd}
```

Witt's Cancellation Theorem
:::

### $f \sim g$ over $\mathbb{Q}$

:::{#thm-q-classification}
## [@serre_course_1973] p. 44, chap. 4, sec. 3.3, theorem 9
Two non-degenerate quadratic forms of rank $n$ over $\mathbb Q$ are equivalent iff they are equivalent over each $\mathbb{Q}_v$.
:::
- Suppose $f \sim g$ over $\mathbb{Q}_v$ for all $v$. Take $a$ represented by $f$ over $\mathbb{Q}$.

- Then $f$ represents $a$ over all $\mathbb{Q}_v$. And $a$ is represented by $g$ over all $\mathbb{Q}_v$, since $f \sim g$ over all $\mathbb{Q}_v$.

- By the Hasse-Minkowski Theorem, $a$ is represented by both $f$ and $g$ over $\mathbb{Q}$.

- Thus $f \sim aZ^2 \oplus f_1$, $g \sim aZ^2 \oplus g_1$, where $\operatorname{rank} f_1 = \operatorname{rank} g_1 = n-1$.

- By Witt's cancellation, we have $f_1 \sim g_1$ over $\mathbb{Q}_v$ for all $v \in \mathbb{V}$.

- By induction on rank $n$, $f_1 \sim g_1$ over $\mathbb{Q}$, thus $f \sim g$ over $\mathbb{Q}$.

# Quadratic Forms over $\mathbb{Q}_v$

## General Ideas

### General Ideas

- Reduce to classifying non-degenerate rank $n$ quadratic forms of the shape $f \sim \sum_{i=1}^n a_i X_i^2$, where $a_i\in K^\times/(K^\times)^2$.

    - Invariant rank: non-degenerate.

    - Symmetric matrices: diagonal.

    - $\sum a_i b_i^2 X_i^2 \sim \sum a_i X_i^2$: squared-free.

\vspace{0.5cm}

- If $f \sim g$, $\det(A_f) = \det(P^T A_g P) = \det(A_g) \det(P)^2$
    - Invariant discriminant: $d = \det(A)$ in $K^\times/(K^\times)^2$.

\vspace{0.5cm}

- $\mathbb{R}^\times / (\mathbb{R}^\times)^2 \cong \{1, -1\}$.
- $\mathbb{Q}_p^\times / (\mathbb{Q}_p^\times)^2 \cong K_4 = \{1, a, p, ap\}$.


## Classification of Quadratic Forms over $\mathbb R$

### Case over $\mathbb R$

- Invariants:
    - Rank: $\operatorname{rank}f = n$.
    - Signature: $(r,s):=(\#\text{positive eigenvalues},\#\text{negative eigenvalues})$.

\vspace{0.7cm}

:::{#thm-Sylvester}
## Sylvester’s law of inertia
Let $f=\sum_{i,j=1}^na_{ij}X_iX_j$ be a quadratic form of rank $n$ over $\mathbb R$. Then
$$
f\sim X_1^2+X_2^2+\cdots+X_r^2-X_{r+1}^2-\cdots-X_{r+s}^2.
$$
:::

<!--
By diagonalizing via congruence and factoring out squares on the diagonal, we see that the only invariants for classifying real quadratic forms are:
-->

## Invariants that Determine the Representation over $\mathbb Q_p$

### Binary Quadratic Forms over $\mathbb Q_{p\neq2}$

:::{#thm-classification}
Two quadratic forms of rank $2$ over $\mathbb Q_{p\neq2}$ are equivalent iff they have the same discriminant $d$ and a common representive number $a$.
:::

\vspace{0.7cm}

- Take $a$ represented by both $f$ and $g$.

\vspace{0.4cm}

- $f\sim f_1\oplus aZ^2$ where $\operatorname{rank}f_1=1$.

\vspace{0.4cm}

- Then $f_1=adX^2$. Thus $f$ is determined. Similarly for $g$.

### Binary Quadratic Forms over $\mathbb Q_{p\neq2}$

- $\textcolor{blue}{a}$: Same color, same equivalent class
  - mutually distinct if colored black
- $\boxed{a}$: Boxed quadratic forms cannot represent $1$

:::{#tbl-disc layout-ncol=2}

| $d$ | $1$ | $a$ | $p$ | $a p$ |
|:-----:|:-----:|:-------------:|:-------:|:---------------:|
| $1$ | $\textcolor{blue}1$ | $a$ | $p$ | $a p$ |
| $a$ |  |  $\textcolor{blue}1$  | $\boxed{a p}$ |  $\boxed{p}$  |
| $p$   |  |  |   $\textcolor{blue}1$   | $\boxed{a}$ |
| $a p$ |  |  |  |  $\textcolor{blue}1$  |

: $p \equiv 1 \pmod 4$ {#tbl-disc-p1}

| $d$ | $1$ | $a$ | $p$ | $a p$ |
|:-----:|:-----:|:-------------:|:-------:|:---------------:|
| $1$ | $\textcolor{blue}1$ | $\textcolor{red}a$ | $p$ | $a p$ |
| $a$ |  |  $\textcolor{blue}1$  | $\boxed{a p}$ |  $\boxed{p}$  |
| $p$   |  |  |   $\boxed{\textcolor{green}1}$   | $\textcolor{red}a$ |
| $a p$ |  |  |  |  $\boxed{\textcolor{green}1}$  |

: $p \equiv 3 \pmod 4$ {#tbl-disc-p3}

Equivalent classes of nondegenerate quadratic forms over $\mathbb Q_{p \neq 2}$, $n=2$  
:::



### Hilbert Symbol

$$
\begin{aligned}
f = aX^2 + bY^2 &\text{ represents } 1 \\
\iff \\
Z^2 - aX^2 - bY^2 &\text{ represents } 0.
\end{aligned}
$$

\vspace{0.7cm}

- Hilbert symbol:
$$
(a, b) = 
\begin{cases}
1 & \text{$Z^2-aX^2-bY^2$ represents 0}, \\
-1 & \text{Otherwise}.
\end{cases}
$$

### Computation of Hilbert Symbol

:::{#tbl-disc layout-ncol=2}

| $(\cdot,\cdot)$ | $1$ | $a$ | $p$ | $a p$ |
|:-----:|:-----:|-------------:|-------:|---------------:|
| $1$ | $1$ | $1$ | $1$ | $1$ |
| $a$ |  |  $1$  | $-1$ |  $-1$  |
| $p$   |  |  |   $1$   | $-1$ |
| $a p$ |  |  |  |  $1$  |

: $p \equiv 1 \pmod 4$ {#tbl-disc-p1}

| $(\cdot,\cdot)$ | $1$ | $a$ | $p$ | $a p$ |
|:-----:|:-----:|-------------:|-------:|---------------:|
| $1$ | $1$ | $1$ | $1$ | $1$ |
| $a$ |  |  $1$  | $-1$ |  $-1$  |
| $p$   |  |  |   $-1$   | $1$ |
| $a p$ |  |  |  |  $-1$  |

: $p \equiv 3 \pmod 4$ {#tbl-disc-p3}

Hilbert Symbol of $\mathbb Q_{p\neq2}$
:::

- Hilbert symbol is a symmetric non-degenerate bilinear form.

### Hasse Invariant

- $f=a_1X_1^2+\cdots+a_nX_n^2$.

\vspace{0.2cm}

- Hasse invariant: $\varepsilon(f)=\prod_{i<j}(a_i,a_j)$


    
\vspace{1cm}

- $f_1=a_2X_2^2+\cdots+a_nX_n^2$.

\vspace{0.2cm}

- $d(f)=\prod_{i=1}^na_i=a_1\prod_{i=2}^na_i=a_1d(f_1)$.

\vspace{0.1cm}

- $\varepsilon(f)=\prod_{1\leq i<j\leq n}(a_i,a_j)=\varepsilon(f_1)\cdot(a_1,a_2\cdots a_n)=\varepsilon(f_1)\cdot(a_1,a_1d(f))$.

### Condition for a quadratic form to represent $0$ or $a$ over $\mathbb Q_p$

<!--*This involves a lot of tedious casework, so we will omit all details due to time constraints.-->


- $f$ represents $0$ iff:
    - For $n=2$: $d=-1$;
    - For $n=3$: $(-1,-d)= \varepsilon$;
    - For $n=4$: $d \neq 1$ or $d=1$ and $\varepsilon = (-1,-1)$;
    - For $n\geq5$: no conditions.

\vspace{0.5cm}

By applying the result to $f_a=f \oplus -aZ^2$, we obtain:

\vspace{0.5cm}

- $f$ represents $a\in \mathbb Q_p^\times/(\mathbb Q_p^\times)^2$ iff:
    - For $n=1$: $a=d$;
    - For $n=2$: $( a,-d ) = \varepsilon$;
    - For $n=3$: $a \neq d$ or $a=d$ and $\varepsilon = ( -1,-d )$;
    - For $n\geq4$: no conditions.


<!--Therefore, the set of numbers represented by a quadratic form $f$ is completely determined by its discriminant and Hasse invariant.-->

## Classification of Quadratic Forms over $\mathbb Q_p$

### $f \sim g$ over $\mathbb{Q}_p$

:::{#thm-qp-classification}
## ([@serre_course_1973] p. 39, chap. 4, sec. 2.3, theorem 7)

Two non-degenerate quadratic forms of rank $n$ over $\mathbb Q_p$ are equivalent iff they have the same discriminant $d$ and Hasse invariant $\varepsilon$.
:::

- $f,g$ have same $d$ and $\varepsilon$, thus there exists $a\in \mathbb Q_p^\times$ which both represented by $f$ and $g$.

- Then $f \sim f_1 \oplus aZ^2$, where $f_1$ is of rank $n-1$. Similarly for $g$.

- $d$ and $\varepsilon$ of $f_1$ can be determined:
  
  - $d(f_1) = a d(f) = a d(g) = d(g_1)$
  - $\varepsilon(f_1) = \varepsilon(f) \cdot (a, a d(f)) = \varepsilon(g) \cdot (a, a d(g)) = \varepsilon(g_1)$

- Thus $f_1, g_1$ share the same $d$ and $\varepsilon$. QED by induction.

# Appendix

## Classification Results

### Classification of Quadratic Forms over $\mathbb{Q}_p$

The invariants $d$ and $\varepsilon$ satisfy the following relations:


:::: {.columns}
::: {.column width="50%"}

- For $n=1$: $\varepsilon=1$;

- For $n=2$: $d\neq-1$ or $\varepsilon=1$;

- For $n\geq3$: no conditions.
:::
::: {.column width="50%"}
- $n=1$: $f=dX^2$

- $n=2$: $f=aX^2+adY^2$

- $n=3$: $f=g\oplus aZ^2$ 
    - $d(g)=ad$ 
    - $\varepsilon(g)=\varepsilon(a,-d)$
:::
::::

- $n>3$: $f=g(X_1,X_2,X_3)\oplus X_4^2\oplus\cdots\oplus X_n^2$
    - $d(g)=d$ and $\varepsilon(g)=\varepsilon$

### Classification of Quadratic Forms over $\mathbb{Q}$

:::{#thm-product-formula}
## Product formula
$(a,b)_v=1$ for almost all $v\in \mathbb{V}$ and $\prod_{v\in\mathbb{V}}(a,b)_v=1$
:::

The invariants $d_v$ and $\varepsilon_v$ satisfy the following relations:

\vspace{0.1cm}

- $\varepsilon_v=1$ for almost $v\in\mathbb V$, and $\prod_{v\in\mathbb{V}}\varepsilon_v=1$.

\vspace{0.1cm}

- $\varepsilon_v=1$ if $n=1$ and if $n=2$ and if the image $d_v$ of $d$ in $\mathbb Q_p^\times/{\mathbb Q_p^\times}^2$ is equal to $-1$.

\vspace{0.1cm}

- $r,s\geq 0$ and $r+s=\operatorname{rank}$.

\vspace{0.1cm}

- $d_\infty=(-1)^s$

\vspace{0.1cm}

- $\varepsilon_\infty=(-1)^{s(s-1)/2}$


## Proof of Hasse-Minkowski Theorem

### Skeleton of Proof

:::{#thm-hasse-minkowski}
## Hasse-Minkowski
$f$ represents $0$ over $\mathbb Q$ iff it represents $0$ over $\mathbb R$ and all $\mathbb Q_p$.
:::

Skeleton of Proof:

\vspace{0.2cm}

- n=2: Fermat's Two-Square Theorem.

\vspace{0.2cm}

- n=3：Gauss's Three-Square Theorem.

\vspace{0.2cm}

- n=4：Lagrange's Four-Square Theorem.

\vspace{0.2cm}

- n≥5: Mathematical induction.